---
title: "Data Exploration of Datasets VCE AI TOOL"
author: "Nebiyou Mengistu"
date: "2026-06-08"
output: html_document
---

```{r}
library(readr)
library(tidyverse)
library(dplyr)
################ HERE I AM LOOKING AT VGIN'S VIRGINIA HOSPITALS DATASET####################
va_hospitals = read.csv("~/VCE_AI_TOOL/data/sources/Virginia-Geographic-Information-Network/Virginia_Hospitals.csv") # VGIN Virginia Hospitals dataset
va_hospitals
```


```{r}
srctype_missingness = mean(is.na(va_hospitals$SrcTyp) | va_hospitals$SrcTyp == "-") * 100
srctype_missingness
# Source of admission to hospitals is missing for 11% of our data
```


```{r}
missingness <- sapply(va_hospitals, function(col) {
  mean(is.na(col) | trimws(col) == "-") * 100
})

missingness

# URL and phone number should probably be omitted

unique_admission = unique(va_hospitals$SrcTyp)
unique_admission
```


```{r}
va_hospitals <- va_hospitals %>% select(LandmkName, Address, City, Zip, X, Y, LastCheck, SrcTyp, FIPScode, FIPSname) # dropped phone and url, most are missing and irrelevant
# also dropped some others, doesn't help the user filter whtasoever, irrelevant


unique_type = unique(va_hospitals$PlaceType)
unique_type

View(va_hospitals)

write.csv(va_hospitals, "~/VCE_AI_TOOL/data/outcome/Virginia-Geographic-Information-Network/vgin_hospitals.csv", row.names = FALSE)
```


```{r}
################## HERE I AM LOOKING AT VDH PUD REPORTABLE DISEASES DATASET ####################

pud_disease = read.csv("PUD Reportable Disease.csv") # primarily looking to see if there are discrepancies between geographic value and FIPS Code

filtered <- pud_disease %>%
  filter(
    grepl("Eastern|Northern|Northwest|Southwest|Central", Geography.Value, ignore.case = FALSE), 
    # This sees if certain regions like Southern or Northern have FIPS Codes. If they don't have an FIPS Code they're not useful
    !grepl("County", Geography.Value, ignore.case = TRUE),   # Geography Value does NOT contain County
    !is.na(FIPS),                                            # FIPS is not NA
    FIPS != ""                                               # FIPS is not empty
  )

# The regions that do not have a county name in the Geography Value column (and have a region like Eastern) all DO NOT have an FIPS Code.
# This makes sense. Since we CANNOT map them to specific counties, I will most likely filter them out for our dataset
# (Not as specific as county)

nrow(filtered)


missing_geo <- pud_disease # wanted to see the unique values of the Geographic names that don't have an FIPS code 
  filter(is.na(FIPS) | str_trim(FIPS) == "") %>% 
  distinct(Geography.Value)

View(missing_geo) ## it's only regions (Northern, Eastern, etc) and State of Virginia. 
## We are good to go!

missing_yearly = sum(is.na(pud_disease$Annual.Case.Count))
missing_yearly # No missing values from Annual Case Count 

missing_rate = sum(is.na(pud_disease$Incidence.Rate))
missing_rate # No missing values from Incidence Rate


library(dplyr)

region_counts <- pud_disease %>%
  filter(grepl("Eastern|Northern|Northwest|Southwest", Geography.Value)) %>%
  count(Geography.Value) 



View(pud_disease)
```


